//
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO
// THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
// PARTICULAR PURPOSE.
//
// Copyright (c) Microsoft Corporation. All rights reserved.
//

DEFINE_GUID(CLSID_CSample, 0x74a23de2, 0xb81d, 0x46ec, 0xe1, 0x29, 0xcd, 0x32, 0x50, 0x7e, 0xd7, 0x16);
