#include "PAMHelper.h"

#include <spdlog/spdlog.h>

#include "shell/Shell.h"
#include "utils/I18n.h"
#include "utils/StringUtils.h"

#ifdef APPLE
#include <chrono>
#include <thread>

#include "platform/PlatformHelper.h"
#include "shell/LocalShell.h"
#include "storage/AppSettings.h"
#endif

#define PAM_CONFIG_DIR std::filesystem::path("/etc/pam.d/")

constexpr std::string_view PAM_CONFIG_GEN_ENTRY = "## Generated by PulseUnlock";
constexpr std::string_view PAM_CONFIG_GEN_ENTRY_OLD = "## Generated by PC Bio Unlock";
constexpr std::string_view PAM_CONFIG_GEN_COMMON = R"(
#%PAM-1.0
{0}
{1}

auth include common-auth
account include common-account
password include common-password
session include common-session
)";
constexpr std::string_view PAM_CONFIG_GEN_SYSTEM = R"(
#%PAM-1.0
{0}
{1}

auth include system-auth
account include system-auth
password include system-auth
session include system-auth
)";

#ifdef APPLE
constexpr auto TERMINAL_TIMEOUT = std::chrono::minutes(5);
constexpr auto TERMINAL_POLL_INTERVAL = std::chrono::milliseconds(500);
#endif

PAMHelper::PAMHelper(const std::function<void(const std::string &)> &logCallback) {
  m_Logger = logCallback;
}

bool PAMHelper::HasConfigEntry(const std::string &configName, const std::string &entry) {
  auto configPath = PAM_CONFIG_DIR / configName;
  if(std::filesystem::exists(configPath)) {
    auto fileData = Shell::ReadBytes(configPath);
    auto fileStr = std::string(fileData.begin(), fileData.end());
    return fileStr.contains(entry);
  }
  return false;
}

void PAMHelper::SetConfigEntry(const std::string &configName, const std::string &entry, bool enabled) {
  auto configPath = PAM_CONFIG_DIR / configName;
  auto hasEntry = ConfigExists(configPath) && ReadConfig(configPath).contains(entry);
  if(enabled && !hasEntry) {
    if(configName == "polkit-1") {
      m_Logger("Disabling polkit-agent-helper restrictions...");
      SetPolkitRestrictions(false);
    }
    AddToConfig(configName, entry);
  } else if(!enabled && hasEntry) {
    RemoveFromConfig(configName, entry);
    if(configName == "polkit-1") {
      m_Logger("Enabling polkit-agent-helper restrictions...");
      SetPolkitRestrictions(true);
    }
  }
}

void PAMHelper::Commit() {
  std::map<std::filesystem::path, std::optional<std::string>> changes{};
  for(const auto &[path, data] : m_PendingChanges) {
    auto exists = std::filesystem::exists(path);
    if(!data.has_value() && !exists)
      continue;
    if(data.has_value() && exists) {
      auto fileData = Shell::ReadBytes(path);
      if(std::string(fileData.begin(), fileData.end()) == data.value())
        continue;
    }
    changes[path] = data;
  }
  m_PendingChanges.clear();
  if(changes.empty())
    return;

#ifdef APPLE
  if(!LocalShell::IsRunningAsAdmin()) {
    CommitWithTerminal(changes);
    return;
  }
#endif
  for(const auto &[path, data] : changes) {
    if(data.has_value()) {
      if(!Shell::WriteBytes(path, {data->begin(), data->end()}))
        throw std::runtime_error(I18n::Get("error_file_write", path.string()));
    } else if(!Shell::Remove(path)) {
      throw std::runtime_error(I18n::Get("error_file_remove", path.string()));
    }
  }
}

bool PAMHelper::ConfigExists(const std::filesystem::path &filePath) {
  if(m_PendingChanges.contains(filePath))
    return m_PendingChanges.at(filePath).has_value();
  return std::filesystem::exists(filePath);
}

std::string PAMHelper::ReadConfig(const std::filesystem::path &filePath) {
  if(m_PendingChanges.contains(filePath))
    return m_PendingChanges.at(filePath).value_or("");
  auto fileData = Shell::ReadBytes(filePath);
  return {fileData.begin(), fileData.end()};
}

bool PAMHelper::IsConfigGenerated(const std::filesystem::path &filePath) {
  auto fileStr = ReadConfig(filePath);
  return fileStr.contains(PAM_CONFIG_GEN_ENTRY) || fileStr.contains(PAM_CONFIG_GEN_ENTRY_OLD);
}

void PAMHelper::AddToConfig(const std::string &configName, const std::string &entry) {
  auto configPath = PAM_CONFIG_DIR / configName;
  if(ConfigExists(configPath)) {
    AddEntryToFile(configPath, entry);
    return;
  }

  m_Logger(fmt::format("Generating configuration {}...", configName));
#ifdef APPLE
  m_PendingChanges[configPath] = fmt::format("{}\n{}\n", PAM_CONFIG_GEN_ENTRY, entry);
#else
  auto hasCommonAuth = std::filesystem::exists(PAM_CONFIG_DIR / "common-auth");
  auto hasSystemAuth = std::filesystem::exists(PAM_CONFIG_DIR / "system-auth");
  if(hasSystemAuth)
    m_PendingChanges[configPath] = fmt::format(PAM_CONFIG_GEN_SYSTEM, entry, PAM_CONFIG_GEN_ENTRY);
  else
    m_PendingChanges[configPath] = fmt::format(PAM_CONFIG_GEN_COMMON, entry, PAM_CONFIG_GEN_ENTRY);
  if(!hasCommonAuth && !hasSystemAuth)
    m_Logger("Unknown PAM configuration. Please report on GitHub.");
#endif
}

void PAMHelper::RemoveFromConfig(const std::string &configName, const std::string &entry) {
  auto configPath = PAM_CONFIG_DIR / configName;
  if(!ConfigExists(configPath))
    return;

#ifdef APPLE
  RemoveEntryFromFile(configPath, entry);
  if(IsConfigGenerated(configPath) && StringUtils::Trim(ReadConfig(configPath)) == PAM_CONFIG_GEN_ENTRY) {
    m_Logger(fmt::format("Removing generated configuration {}...", configName));
    m_PendingChanges[configPath] = {};
  }
#else
  if(IsConfigGenerated(configPath)) {
    m_Logger(fmt::format("Removing generated configuration {}...", configName));
    m_PendingChanges[configPath] = {};
  } else {
    RemoveEntryFromFile(configPath, entry);
  }
#endif
}

void PAMHelper::AddEntryToFile(const std::filesystem::path &filePath, const std::string &entry) {
  auto fileStr = ReadConfig(filePath);

  m_Logger(fmt::format("Adding PAM entry to {}...", filePath.string()));
  std::string resultStr{};
  auto hasBegin = fileStr.contains("#%PAM-1.0\n");
  if(!hasBegin) {
    resultStr.append("#%PAM-1.0\n");
    resultStr.append(entry + '\n');
  }

  for(const auto &line : StringUtils::Split(fileStr, "\n")) {
    if(line == "#%PAM-1.0" && hasBegin) {
      resultStr.append(line + '\n');
      resultStr.append(entry + '\n');
    } else {
      resultStr.append(line + '\n');
    }
  }
  while(resultStr.ends_with("\n\n"))
    resultStr.pop_back();
  m_PendingChanges[filePath] = resultStr;
}

void PAMHelper::RemoveEntryFromFile(const std::filesystem::path &filePath, const std::string &entry) {
  auto fileStr = ReadConfig(filePath);
  auto entries = StringUtils::Split(entry, "\n");

  m_Logger(fmt::format("Removing PAM entry from {}...", filePath.string()));
  std::string resultStr{};
  for(const auto &line : StringUtils::Split(fileStr, "\n")) {
    auto shouldRemove = false;
    for(const auto &lineEntry : entries) {
      if(line == lineEntry) {
        shouldRemove = true;
        break;
      }
    }
    if(!shouldRemove)
      resultStr.append(line + '\n');
  }
  while(resultStr.ends_with("\n\n"))
    resultStr.pop_back();
  m_PendingChanges[filePath] = resultStr;
}

bool PAMHelper::SetPolkitRestrictions(bool enabled) {
  auto serviceDirs = {std::filesystem::path("/lib64/systemd/system/"), std::filesystem::path("/lib/systemd/system/"),
                      std::filesystem::path("/usr/lib64/systemd/system/"), std::filesystem::path("/usr/lib/systemd/system/"),
                      std::filesystem::path("/etc/systemd/system/")};
  auto serviceNames = {"polkit-agent-helper@.service", "polkit-agent-helper.service"};
  std::optional<std::filesystem::path> servicePath{};
  for(const auto &path : serviceDirs) {
    for(const auto &name : serviceNames) {
      if(std::filesystem::exists(path / name)) {
        servicePath = path / name;
        goto POLKIT_FOUND;
      }
    }
  }

POLKIT_FOUND:
  if(!servicePath.has_value()) {
    m_Logger("Failed to find polkit-agent-helper service path.");
    return false;
  }
  auto fileData = Shell::ReadBytes(servicePath.value());
  auto fileStr = std::string(fileData.begin(), fileData.end());
  if(enabled) {
    fileStr = StringUtils::Replace(fileStr, "NoNewPrivileges=no", "NoNewPrivileges=yes");
    fileStr = StringUtils::Replace(fileStr, "PrivateDevices=no", "PrivateDevices=yes");
    fileStr = StringUtils::Replace(fileStr, "PrivateNetwork=no", "PrivateNetwork=yes");
    fileStr = StringUtils::Replace(fileStr, "#RestrictAddressFamilies=AF_UNIX", "RestrictAddressFamilies=AF_UNIX");
    fileStr = StringUtils::Replace(fileStr, "RestrictSUIDSGID=no", "RestrictSUIDSGID=yes");
    fileStr = StringUtils::Replace(fileStr, "#DeviceAllow=", "DeviceAllow=");
    fileStr = StringUtils::Replace(fileStr, "#DevicePolicy=strict", "DevicePolicy=strict");
  } else {
    fileStr = StringUtils::Replace(fileStr, "NoNewPrivileges=yes", "NoNewPrivileges=no");
    fileStr = StringUtils::Replace(fileStr, "PrivateDevices=yes", "PrivateDevices=no");
    fileStr = StringUtils::Replace(fileStr, "PrivateNetwork=yes", "PrivateNetwork=no");
    fileStr = StringUtils::Replace(fileStr, "RestrictAddressFamilies=AF_UNIX", "#RestrictAddressFamilies=AF_UNIX");
    fileStr = StringUtils::Replace(fileStr, "RestrictSUIDSGID=yes", "RestrictSUIDSGID=no");
    fileStr = StringUtils::Replace(fileStr, "DeviceAllow=", "#DeviceAllow=");
    fileStr = StringUtils::Replace(fileStr, "DevicePolicy=strict", "#DevicePolicy=strict");
  }
  if(!Shell::WriteBytes(servicePath.value(), {fileStr.begin(), fileStr.end()})) {
    m_Logger(I18n::Get("error_file_write", servicePath.value().string()));
    return false;
  }
  return true;
}

#ifdef APPLE
void PAMHelper::CommitWithTerminal(const std::map<std::filesystem::path, std::optional<std::string>> &changes) {
  auto id = StringUtils::RandomString(16, false);
  if(id.empty())
    throw std::runtime_error(I18n::Get("error_mac_pam_update", I18n::Get("product_name")));
  auto stagingDir = AppSettings::GetBaseDir() / "pam-staging" / id;
  auto applyFile = stagingDir / "apply.sh";
  auto commandFile = stagingDir / "update.command";
  auto statusFile = PlatformHelper::GetTempDir() / fmt::format("pcbu-pam-{}.status", id);
  auto cleanup = [&]() {
    Shell::RunCommand(fmt::format("rm -rf {}", StringUtils::ShellQuote(stagingDir.string())));
    LocalShell::Remove(statusFile);
  };

  m_Logger("Updating PAM configuration...");
  if(!Shell::CreateDir(stagingDir))
    throw std::runtime_error(I18n::Get("error_file_write", stagingDir.string()));

  std::string applyScript = "#!/bin/bash\nset -e\n";
  std::string fileList{};
  auto fileIdx = 0;
  for(const auto &[path, data] : changes) {
    auto target = StringUtils::ShellQuote(path.string());
    if(data.has_value()) {
      auto stagedFile = stagingDir / fmt::format("file{}", fileIdx++);
      if(!Shell::WriteBytes(stagedFile, {data->begin(), data->end()})) {
        cleanup();
        throw std::runtime_error(I18n::Get("error_file_write", stagedFile.string()));
      }
      applyScript += fmt::format("/usr/bin/install -S -m 0644 -o root -g wheel {} {}\n", StringUtils::ShellQuote(stagedFile.string()), target);
    } else {
      applyScript += fmt::format("/bin/rm -f {}\n", target);
    }
    fileList += fmt::format("printf '  %s\\n' {}\n", target);
  }

  auto commandScript = fmt::format(R"SH(#!/bin/bash
STATUS_FILE={0}
trap 'echo failed > "$STATUS_FILE"; exit 1' HUP INT TERM
clear
printf '%s\n\n' {1}
{2}
printf '\n%s\n\n' {3}
if /usr/bin/sudo /bin/bash {4}; then
  echo ok > "$STATUS_FILE"
  printf '\n%s\n' {5}
  TTY_PATH="$(tty)"
  (/usr/bin/osascript -e 'on run argv' -e 'tell application "Terminal"' -e 'repeat with w in windows' \
    -e 'if tty of selected tab of w is item 1 of argv then' -e 'close w' -e 'exit repeat' -e 'end if' \
    -e 'end repeat' -e 'if (count of windows) is 0 then quit' -e 'end tell' -e 'end run' "$TTY_PATH" >/dev/null 2>&1 &)
  exit 0
fi
echo failed > "$STATUS_FILE"
printf '\n%s\n' {6}
exit 1
)SH",
                                   StringUtils::ShellQuote(statusFile.string()), StringUtils::ShellQuote(I18n::Get("mac_pam_terminal_intro", I18n::Get("product_name"))), fileList,
                                   StringUtils::ShellQuote(I18n::Get("mac_pam_terminal_instructions")), StringUtils::ShellQuote(applyFile.string()),
                                   StringUtils::ShellQuote(I18n::Get("mac_pam_terminal_success")), StringUtils::ShellQuote(I18n::Get("mac_pam_terminal_failed", I18n::Get("product_name"))));

  auto stagingDirStr = StringUtils::ShellQuote(stagingDir.string());
  if(!Shell::WriteBytes(applyFile, {applyScript.begin(), applyScript.end()}) ||
     !Shell::WriteBytes(commandFile, {commandScript.begin(), commandScript.end()}) ||
     Shell::RunCommand(fmt::format("chown -R root:wheel {0} && chmod 755 {1} {0} && chmod 644 {0}/* && chmod 755 {2}", stagingDirStr,
                                   StringUtils::ShellQuote(stagingDir.parent_path().string()), StringUtils::ShellQuote(commandFile.string())))
             .exitCode != 0) {
    cleanup();
    throw std::runtime_error(I18n::Get("error_file_write", stagingDir.string()));
  }

  if(LocalShell::RunUserCommand(fmt::format("open -a Terminal {}", StringUtils::ShellQuote(commandFile.string()))).exitCode != 0) {
    cleanup();
    throw std::runtime_error(I18n::Get("error_mac_pam_update", I18n::Get("product_name")));
  }
  m_Logger(I18n::Get("mac_pam_terminal_waiting"));

  std::string status{};
  auto deadline = std::chrono::steady_clock::now() + TERMINAL_TIMEOUT;
  while(status.empty() && std::chrono::steady_clock::now() < deadline) {
    std::this_thread::sleep_for(TERMINAL_POLL_INTERVAL);
    if(!std::filesystem::exists(statusFile))
      continue;
    auto statusData = LocalShell::ReadBytes(statusFile);
    status = StringUtils::Trim(std::string(statusData.begin(), statusData.end()));
  }
  cleanup();
  if(status != "ok") {
    spdlog::error("PAM update in Terminal did not succeed. (Status={})", status.empty() ? "timeout" : status);
    throw std::runtime_error(I18n::Get("error_mac_pam_update", I18n::Get("product_name")));
  }

  for(const auto &[path, data] : changes) {
    auto exists = std::filesystem::exists(path);
    auto isApplied = data.has_value() ? exists && ReadConfig(path) == data.value() : !exists;
    if(!isApplied) {
      spdlog::error("PAM file was not updated. (Path={})", path.string());
      throw std::runtime_error(I18n::Get("error_mac_pam_update", I18n::Get("product_name")));
    }
  }
}
#endif

/*
 * Migration
 */

void PAMHelper::MigrateConfigEntry(const std::string &configName, const std::string &oldEntry, const std::string &newEntry) {
  auto configPath = PAM_CONFIG_DIR / configName;
  if(!ConfigExists(configPath))
    return;

  auto fileStr = ReadConfig(configPath);
  auto migrated = false;
  if(fileStr.contains(PAM_CONFIG_GEN_ENTRY_OLD)) {
    fileStr = StringUtils::Replace(fileStr, std::string(PAM_CONFIG_GEN_ENTRY_OLD), std::string(PAM_CONFIG_GEN_ENTRY));
    migrated = true;
  }
  if(fileStr.contains(oldEntry)) {
    m_Logger(fmt::format("Migrating PAM entry in {}...", configPath.string()));
    fileStr = StringUtils::Replace(fileStr, oldEntry, newEntry);
    migrated = true;
  }
  if(!migrated)
    return;
  m_PendingChanges[configPath] = fileStr;
}
