FROM --platform=linux/aarch64 debian:bookworm
RUN apt-get update && apt-get install -y build-essential pkg-config cmake git wget libfuse2 gcc-11 g++-11
#RUN apt-get install -y qt6-base-dev qt6-declarative-dev qt6-tools-dev qmake6 qml6-module-*
RUN apt-get install -y python3 python3-pip pipx libdbus-1-3 libpulse-mainloop-glib0 libgl1-mesa-dev libegl1-mesa libsm6 libxrender1 libfontconfig1 libxkbcommon-x11-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinerama0-dev libxcb-xfixes0-dev libxcb-cursor-dev file
RUN apt-get install -y libssl-dev libpam-dev libbluetooth-dev
RUN apt-get install -y qemu-user-static

RUN pipx install aqtinstall
ARG QT=6.7.2
ARG QT_HOST=linux_arm64
ARG QT_TARGET=desktop
ARG QT_ARCH=linux_gcc_arm64
RUN ~/.local/bin/aqt install-qt --outputdir /opt/qt ${QT_HOST} ${QT_TARGET} ${QT} ${QT_ARCH}
ENV PATH /opt/qt/${QT}/gcc_arm64/bin:$PATH
ENV QT_PLUGIN_PATH /opt/qt/${QT}/gcc_arm64/plugins/
ENV QML_IMPORT_PATH /opt/qt/${QT}/gcc_arm64/qml/
ENV QML2_IMPORT_PATH /opt/qt/${QT}/gcc_arm64/qml/

WORKDIR /project
COPY . .
WORKDIR /project/pkg
RUN chmod +x build-desktop.sh
ENTRYPOINT ["bash", "-c", "cd /project/pkg && ARCH=arm64 QT_BASE_DIR=/opt/qt/6.7.2 DOCKER_BUILD=1 ./build-desktop.sh"]
