function(add_version_resource TARGET DESCRIPTION)
    get_target_property(TARGET_TYPE ${TARGET} TYPE)
    if(TARGET_TYPE STREQUAL "SHARED_LIBRARY")
        set(VERSION_FILE_TYPE VFT_DLL)
        set(VERSION_FILE_NAME ${TARGET}${CMAKE_SHARED_LIBRARY_SUFFIX})
    else()
        set(VERSION_FILE_TYPE VFT_APP)
        set(VERSION_FILE_NAME ${TARGET}${CMAKE_EXECUTABLE_SUFFIX})
    endif()
    set(VERSION_DESCRIPTION ${DESCRIPTION})
    set(VERSION_RC ${CMAKE_CURRENT_BINARY_DIR}/${TARGET}_version.rc)
    configure_file(${CMAKE_CURRENT_FUNCTION_LIST_DIR}/version.rc.in ${VERSION_RC} @ONLY)
    target_sources(${TARGET} PRIVATE ${VERSION_RC})
endfunction()
